[mysql.new_example]
address = "192.168.2.3:3306"
username = "root"
password = "liushuojia"
database = "new_example"

[mysql.example]
address = "192.168.2.3:3306"
username = "root"
password = "liushuojia"
database = "example"
