
[token.access]
key = "a1ab2bc3cd4de5ef6fg7g0011223344556677889900123465u11222ser"
#expire = "10m"
expire = "24h"
issuer = "quantify"


[token.refresh]
key = "aabbccddeeffgg0011223344556677889900user112233"
#expire = "12h"
expire = "240h"
issuer = "quantify"


[minio.local]
address = "192.168.2.3:9000"
access = "BD4SOlUQ8npTbGtLdgPV"
secret = "30KlHODmQxsaSrQxd3wkZSET1UZ4fkct0jz6pEyI"
useSSL = false
bucket = "example-test"


[minio.default]
address = "minio.yunjitrip.com"
access = "4Sg021YTfzKGWigg3KHa"
secret = "XGkdQF7nWRhRNTI3f4fRgxSkvvIq1aEtxoLHkv9b"
useSSL = false
bucket = "example"


[[email.code]]
account = "riskalertbot-1@Balancev.com"
name = "百仁思"
passwd = "rauB7AZWCXv65ztf"
smtp = "smtp.feishu.cn"
port = 465


[[email.code]]
account = "liushuojia@qq.com"
name = "刘硕嘉"
passwd = "sdrnabekkxgwbiih"
smtp = "smtp.qq.com"
port = 465
